name: cifar_dataset_6_classes_input_permuted_output_permuted_v1
_target_: src.data.filesystem.dataloader.build_dataloaders
_recursive_: False
train_config:
  dataset:
    dir: ${setup.base_path}/data/processed
  dataloader:
    batch_size: 128
    shuffle: True
    num_workers: 6
    pin_memory: True
test_config:
  dataset:
    dir: ${setup.base_path}/data/processed
  dataloader:
    batch_size: 256
    shuffle: False
    num_workers: 6
    pin_memory: True