name: mnist
_target_: src.data.mnist.dataloader.build_dataloaders
train_config:
  dataset:
    root: ${setup.base_path}/data/mnist
    train: True
    download: True
  dataloader:
    batch_size: 128
    shuffle: True
    num_workers: 6
    pin_memory: True
test_config:
  dataset:
    root: ${setup.base_path}/data/mnist
    train: False
  dataloader:
    batch_size: 256
    shuffle: False
    num_workers: 6
    pin_memory: True
